const { Schema, model } = require('mongoose');

//schema
const PizzaSchema = new Schema({
    // note: MongoDB ObjectID or _id will be autogenerated, no need to add to model
    pizzaName: {
      type: String
    },
    createdBy: {
      type: String
    },
    createdAt: {    // will auto-generate per Date.now, no need to add to JSON in POST
      type: Date,
      default: Date.now
    },
    size: {
      type: String,
      default: 'Large'
    },
    toppings: []    //array of toppings
  });

  // create the Pizza model using the PizzaSchema
const Pizza = model('Pizza', PizzaSchema);

  // export the Pizza model
module.exports = Pizza;